ARTIFACT=wrapper-pattern
ARCHIVE=$(ARTIFACT).tar.gz
VERSION=$(BRANCH)
BUILD_DIR=build
REQUIREMENTS_DIR=$(BUILD_DIR)/requirements
# TODO: Check if TRAVIS_BUILD is true before you use
# TODO: TRAVIS_BUILD_NUMBER.
# TODO: TRAVIS_BRANCH.
BUILD_NUMBER=$(TRAVIS_BUILD_NUMBER)
BRANCH=$(TRAVIS_BRANCH)

clean:
	-ARTIFACT=$(ARTIFACT) \
	ARCHIVE=$(ARCHIVE) \
	VERSION=$(VERSION) \
	BUILD_DIR=$(BUILD_DIR) \
	REQUIREMENTS_DIR=$(REQUIREMENTS_DIR) \
	BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH=$(BRANCH) \
		./clean.sh

build:
	mkdir -p ${REQUIREMENTS_DIR}

	ARTIFACT=$(ARTIFACT) \
	ARCHIVE=$(ARCHIVE) \
	VERSION=$(VERSION) \
	BUILD_DIR=$(BUILD_DIR) \
	REQUIREMENTS_DIR=$(REQUIREMENTS_DIR) \
	BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH=$(BRANCH) \
		./build.sh

test:
	ARTIFACT=$(ARTIFACT) \
	ARCHIVE=$(ARCHIVE) \
	VERSION=$(VERSION) \
	BUILD_DIR=$(BUILD_DIR) \
	REQUIREMENTS_DIR=$(REQUIREMENTS_DIR) \
	BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH=$(BRANCH) \
		./test.sh

publish:
	ARTIFACT=$(ARTIFACT) \
	ARCHIVE=$(ARCHIVE) \
	VERSION=$(VERSION) \
	BUILD_DIR=$(BUILD_DIR) \
	REQUIREMENTS_DIR=$(REQUIREMENTS_DIR) \
	BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH=$(BRANCH) \
		./publish.sh

ci: clean build test publish

.PHONY: test
